apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: dev-cluster
servers: 1
agents: 2
ports:
  - port: 8089:8089
    nodeFilters:
    - loadbalancer
options:
  k3s:
    extraArgs:
      - arg: "--disable=traefik"
        nodeFilters:
        - server:*